# Generated by Django 2.2.4 on 2021-03-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20210316_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2021-03-18', max_length=20, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(upload_to='contact/recruit/%Y_%m_%d', verbose_name='个人照片'),
        ),
    ]
