# Generated by Django 2.2.4 on 2021-03-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynews',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='News/post/', verbose_name='展报'),
        ),
    ]
